import type { Crew, Equipment, MaintenanceRequest, Sector } from "./types";

export const SCHEDULE_DATE = "2026-09-01";

export const seedCrews: Crew[] = [
  {
    id: 1,
    name: "Alpha Crew",
    skills: ["signalling", "electrical"],
    available_start: "00:00",
    available_end: "04:00",
    max_concurrent_jobs: 2,
  },
  {
    id: 2,
    name: "Bravo Crew",
    skills: ["track", "welding", "mechanical"],
    available_start: "00:00",
    available_end: "06:00",
    max_concurrent_jobs: 1,
  },
  {
    id: 3,
    name: "Charlie Crew",
    skills: ["signalling", "track"],
    available_start: "01:00",
    available_end: "05:00",
    max_concurrent_jobs: 1,
  },
];

export const seedEquipment: Equipment[] = [
  { id: 1, name: "work_train", type: "vehicle", available: true },
  { id: 2, name: "welding_kit", type: "tool", available: true },
  { id: 3, name: "signal_tester", type: "instrument", available: true },
  { id: 4, name: "rail_grinder", type: "vehicle", available: false },
  { id: 5, name: "lifting_jack", type: "tool", available: true },
];

export const seedSectors: Sector[] = [
  { id: 1, name: "Track 12", exclusion_zone: ["Track 14"] },
  { id: 2, name: "Track 14", exclusion_zone: ["Track 12"] },
  { id: 3, name: "Station A", exclusion_zone: ["Track 12"] },
  { id: 4, name: "Depot C", exclusion_zone: [] },
];

const D = SCHEDULE_DATE;

export const seedRequests: MaintenanceRequest[] = [
  {
    id: 1,
    title: "Point machine replacement at Track 12 crossover",
    type: "planned",
    location: "Track 12",
    duration_minutes: 120,
    deadline: `${D}T05:00:00`,
    priority_score: 90,
    trust_score: 95,
    final_priority: 92,
    required_skills: ["signalling"],
    required_equipment: ["work_train", "lifting_jack"],
    manpower_count: 4,
    work_compatibility_tags: ["electrical", "mechanical"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 2,
    title: "Anomaly detected: rail vibration on Track 14 (single sensor)",
    type: "predictive",
    location: "Track 14",
    duration_minutes: 90,
    deadline: `${D}T06:00:00`,
    priority_score: 85,
    trust_score: 52,
    final_priority: 72,
    required_skills: ["track"],
    required_equipment: ["signal_tester"],
    manpower_count: 2,
    work_compatibility_tags: ["mechanical"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 3,
    title: "Unusual current draw on Station A escalator 3 feeder",
    type: "predictive",
    location: "Station A",
    duration_minutes: 60,
    deadline: `${D}T05:30:00`,
    priority_score: 70,
    trust_score: 58,
    final_priority: 65,
    required_skills: ["electrical"],
    required_equipment: ["signal_tester"],
    manpower_count: 2,
    work_compatibility_tags: ["electrical"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 4,
    title: "Rail grinding pass Track 12 eastbound",
    type: "routine",
    location: "Track 12",
    duration_minutes: 150,
    deadline: `${D}T06:00:00`,
    priority_score: 55,
    trust_score: 90,
    final_priority: 69,
    required_skills: ["track"],
    required_equipment: ["rail_grinder"],
    manpower_count: 3,
    work_compatibility_tags: ["mechanical", "hot_work"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 5,
    title: "Signal cable insulation test Track 12",
    type: "routine",
    location: "Track 12",
    duration_minutes: 90,
    deadline: `${D}T05:00:00`,
    priority_score: 60,
    trust_score: 90,
    final_priority: 72,
    required_skills: ["signalling"],
    required_equipment: ["signal_tester"],
    manpower_count: 2,
    work_compatibility_tags: ["electrical"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 6,
    title: "Weld repair on crossing nose, Track 14",
    type: "manual",
    location: "Track 14",
    duration_minutes: 120,
    deadline: `${D}T06:00:00`,
    priority_score: 80,
    trust_score: 75,
    final_priority: 78,
    required_skills: ["welding"],
    required_equipment: ["welding_kit", "work_train"],
    manpower_count: 3,
    work_compatibility_tags: ["hot_work"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 7,
    title: "3 sensors agree: bearing wear on Depot C hoist",
    type: "predictive",
    location: "Depot C",
    duration_minutes: 75,
    deadline: `${D}T05:00:00`,
    priority_score: 65,
    trust_score: 88,
    final_priority: 74,
    required_skills: ["mechanical"],
    required_equipment: ["lifting_jack"],
    manpower_count: 2,
    work_compatibility_tags: ["mechanical"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 8,
    title: "Platform screen door alignment, Station A",
    type: "manual",
    location: "Station A",
    duration_minutes: 90,
    deadline: `${D}T04:30:00`,
    priority_score: 75,
    trust_score: 75,
    final_priority: 75,
    required_skills: ["mechanical"],
    required_equipment: ["lifting_jack"],
    manpower_count: 2,
    work_compatibility_tags: ["mechanical"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 9,
    title: "Track circuit retune, Track 14 to Station A approach",
    type: "routine",
    location: "Track 14",
    duration_minutes: 60,
    deadline: `${D}T06:00:00`,
    priority_score: 50,
    trust_score: 90,
    final_priority: 66,
    required_skills: ["signalling"],
    required_equipment: ["signal_tester"],
    manpower_count: 2,
    work_compatibility_tags: ["electrical"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
  {
    id: 10,
    title: "Overnight patrol: water seepage check near Track 12 sump",
    type: "routine",
    location: "Track 12",
    duration_minutes: 45,
    deadline: `${D}T06:00:00`,
    priority_score: 40,
    trust_score: 90,
    final_priority: 60,
    required_skills: ["track"],
    required_equipment: [],
    manpower_count: 1,
    work_compatibility_tags: ["water"],
    status: "pending",
    scheduled_start: null,
    scheduled_end: null,
    assigned_crew_id: null,
    conflict_reason: null,
  },
];
