import { useState } from "react";
import { usePlanning } from "../lib/planning-context";
import { PlanningEmpty, PlanningSummary, ResultExports } from "../components/PlanningViews";
import { Button, Card, CardContent, CardHeader, CardTitle, Input } from "../components/ui";

export default function ScheduleViewer() {
  const { instance, solution, stale, busy, run } = usePlanning();
  const [activity, setActivity] = useState("");
  const [week, setWeek] = useState("");
  const current = stale ? null : solution;
  const matches = (row: { activity_id: string; week: number }) => row.activity_id.toLowerCase().includes(activity.toLowerCase()) && (!week || row.week === Number(week));
  const access = current?.access.filter(matches) ?? [];
  const occupancy = current?.occupancy.filter(matches) ?? [];
  const heading = "whitespace-nowrap p-3 text-xs text-ink/60";
  return <div className="animate-fade-up py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.25em] text-ink/50">PS1 · Result inspection</p><h1 className="mt-3 text-4xl font-black tracking-tight">Weekly access schedule</h1></div><Button onClick={() => void run()} disabled={busy || !instance}>{busy ? "Working…" : "Run scenarios A, B & C"}</Button></div><PlanningSummary />
    {!instance ? <PlanningEmpty /> : !current ? <Card className="mt-6 p-6"><p role="status" className="text-sm text-ink/60">{stale ? "Inputs changed. Run the scenarios again to inspect a current schedule." : "Run the scenarios to inspect access, occupancy and contract completion rows."}</p></Card> : <>
      <div className="mt-6 flex flex-wrap items-end gap-3"><label className="block text-xs text-ink/60">Activity ID<Input aria-label="Filter schedule by activity ID" className="mt-1 max-w-xs" placeholder="All activities" value={activity} onChange={e => setActivity(e.target.value)} /></label><label className="block text-xs text-ink/60">Planning week<Input aria-label="Filter schedule by planning week" className="mt-1 w-40" type="number" min={1} step={1} placeholder="All weeks" value={week} onChange={e => setWeek(e.target.value)} /></label><Button variant="ghost" onClick={() => { setActivity(""); setWeek(""); }}>Clear filters</Button></div>
      <p className="mt-3 text-xs text-ink/60">Access-night numbers are local indices within each planning week. Standard access delivers 1 unit; ECLO delivers 1.5 units.</p>
      <Card className="mt-4"><CardHeader><CardTitle>SCHEDULE_ACCESS · scenario {current.scenario}</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Exact access schedule rows with workload yield</caption><thead><tr>{["Activity", "Access sequence", "Week", "Local access-night", "ECLO", "Access units", "Possession groups", "Occupied locations"].map(h => <th scope="col" key={h} className={heading}>{h}</th>)}</tr></thead><tbody>{access.map((p,i) => {
        const occupied = current.occupancy.filter(o => o.activity_id === p.activity_id && o.week === p.week);
        return <tr key={`${p.activity_id}-${p.access_seq}-${i}`} className="border-t border-ink/10"><th scope="row" className="p-3 font-mono font-normal">{p.activity_id}</th><td className="p-3">{p.access_seq}</td><td className="p-3">{p.week}</td><td className="p-3">{p.access_night}</td><td className="p-3">{p.eclo}</td><td className="p-3">{p.eclo ? 1.5 : 1}</td><td className="p-3">{[...new Set(occupied.map(o => o.co_share_group))].join(", ") || "—"}</td><td className="p-3">{[...new Set(occupied.map(o => o.location_id))].join(", ") || "—"}</td></tr>;
      })}{access.length === 0 && <tr><td colSpan={8} className="p-8 text-center text-ink/50">No access rows match these filters.</td></tr>}</tbody></table></div></CardContent></Card>
      <Card className="mt-6"><CardHeader><CardTitle>SCHEDULE_OCCUPANCY · matching activity / week rows</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Exact schedule occupancy rows</caption><thead><tr>{["Activity", "Week", "Location", "Co-share group"].map(h => <th scope="col" key={h} className={heading}>{h}</th>)}</tr></thead><tbody>{occupancy.map((o,i) => <tr key={`${o.activity_id}-${o.week}-${o.location_id}-${i}`} className="border-t border-ink/10"><th scope="row" className="p-3 font-mono font-normal">{o.activity_id}</th><td className="p-3">{o.week}</td><td className="p-3 font-mono">{o.location_id}</td><td className="p-3 font-mono">{o.co_share_group}</td></tr>)}{occupancy.length === 0 && <tr><td colSpan={4} className="p-8 text-center text-ink/50">No occupancy rows match these filters.</td></tr>}</tbody></table></div></CardContent></Card>
      <Card className="mt-6"><CardHeader><CardTitle>RESULTS · contract completion</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Exact contract completion output rows</caption><thead><tr>{["Scenario", "Contract", "Simulated completion date", "Overrun days"].map(h => <th scope="col" key={h} className={heading}>{h}</th>)}</tr></thead><tbody>{current.results.map(r => <tr key={r.contract_number} className="border-t border-ink/10"><td className="p-3">{r.scenario}</td><th scope="row" className="p-3 font-mono font-normal">{r.contract_number}</th><td className="p-3">{r.simulated_completion_date}</td><td className="p-3">{r.overrun_days}</td></tr>)}</tbody></table></div></CardContent></Card>
    </>}
    <ResultExports />
  </div>;
}
